name: Generate Buzzword

on:
  schedule:
    - cron: '0 */1 * * *'  # Run every hour
  workflow_dispatch:  # Allow manual trigger
  push:
    branches: [ main, master ]  # Run on push to main or master

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is important!
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Generate new buzzword
        run: python generate.py
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add buzzword.json
          git diff --staged --quiet || git commit -m "Generate new buzzword"
          git push
